#!/bin/bash

if dropbox running;
then
        color=kr
else
        color=kg
fi

if dropbox status | grep -q "Up to date";
then
        word=Dbox
else
        if dropbox status | grep -q Downloading;
        then
                word=DbDN
        elif dropbox status | grep -q Uploading;
        then
                word=DbUP
        else
                word=DbER
        fi
fi

echo -e "\005{= $color}$word\005{-}";
